/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.util.ArrayList;
import objects.Carta;
import objects.Partida;

/**
 *
 * @author honda
 */
public class GameScreen extends javax.swing.JFrame {
    private Partida p;
    private String actual_player;

    /**
     * Creates new form GameScreen
     */
    public GameScreen() {
        initComponents();
        p=new Partida();
        btnIniciar.setEnabled(false);
        actual_player="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bgCA = new javax.swing.JPanel();
        subgCA = new javax.swing.JPanel();
        txtCA = new javax.swing.JLabel();
        bgc1 = new javax.swing.JPanel();
        subgc1 = new javax.swing.JPanel();
        txtC1 = new javax.swing.JLabel();
        bgc2 = new javax.swing.JPanel();
        subgc2 = new javax.swing.JPanel();
        txtC2 = new javax.swing.JLabel();
        bgc3 = new javax.swing.JPanel();
        subgc3 = new javax.swing.JPanel();
        txtC3 = new javax.swing.JLabel();
        bgc5 = new javax.swing.JPanel();
        subgc5 = new javax.swing.JPanel();
        txtC5 = new javax.swing.JLabel();
        bgc6 = new javax.swing.JPanel();
        subgc6 = new javax.swing.JPanel();
        txtC6 = new javax.swing.JLabel();
        bgc8 = new javax.swing.JPanel();
        subgc8 = new javax.swing.JPanel();
        txtC8 = new javax.swing.JLabel();
        bgc9 = new javax.swing.JPanel();
        subgc9 = new javax.swing.JPanel();
        txtC9 = new javax.swing.JLabel();
        bgM = new javax.swing.JPanel();
        subgM = new javax.swing.JPanel();
        txtM = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        bgCA.setBackground(new java.awt.Color(0, 0, 0));

        subgCA.setBackground(new java.awt.Color(102, 102, 255));

        txtCA.setFont(new java.awt.Font("Tahoma", 0, 150)); // NOI18N
        txtCA.setForeground(new java.awt.Color(255, 255, 255));
        txtCA.setText("9");

        javax.swing.GroupLayout subgCALayout = new javax.swing.GroupLayout(subgCA);
        subgCA.setLayout(subgCALayout);
        subgCALayout.setHorizontalGroup(
            subgCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgCALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subgCALayout.setVerticalGroup(
            subgCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgCALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgCALayout = new javax.swing.GroupLayout(bgCA);
        bgCA.setLayout(bgCALayout);
        bgCALayout.setHorizontalGroup(
            bgCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgCALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgCALayout.setVerticalGroup(
            bgCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgCALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgc1.setBackground(new java.awt.Color(0, 0, 0));

        subgc1.setBackground(new java.awt.Color(255, 255, 255));

        txtC1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtC1.setText("9");

        javax.swing.GroupLayout subgc1Layout = new javax.swing.GroupLayout(subgc1);
        subgc1.setLayout(subgc1Layout);
        subgc1Layout.setHorizontalGroup(
            subgc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subgc1Layout.setVerticalGroup(
            subgc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgc1Layout = new javax.swing.GroupLayout(bgc1);
        bgc1.setLayout(bgc1Layout);
        bgc1Layout.setHorizontalGroup(
            bgc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgc1Layout.setVerticalGroup(
            bgc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgc2.setBackground(new java.awt.Color(0, 0, 0));

        subgc2.setBackground(subgc1.getBackground());

        txtC2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtC2.setText("9");

        javax.swing.GroupLayout subgc2Layout = new javax.swing.GroupLayout(subgc2);
        subgc2.setLayout(subgc2Layout);
        subgc2Layout.setHorizontalGroup(
            subgc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subgc2Layout.setVerticalGroup(
            subgc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgc2Layout = new javax.swing.GroupLayout(bgc2);
        bgc2.setLayout(bgc2Layout);
        bgc2Layout.setHorizontalGroup(
            bgc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgc2Layout.setVerticalGroup(
            bgc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgc3.setBackground(new java.awt.Color(0, 0, 0));

        subgc3.setBackground(new java.awt.Color(255, 255, 255));

        txtC3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtC3.setText("9");

        javax.swing.GroupLayout subgc3Layout = new javax.swing.GroupLayout(subgc3);
        subgc3.setLayout(subgc3Layout);
        subgc3Layout.setHorizontalGroup(
            subgc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subgc3Layout.setVerticalGroup(
            subgc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgc3Layout = new javax.swing.GroupLayout(bgc3);
        bgc3.setLayout(bgc3Layout);
        bgc3Layout.setHorizontalGroup(
            bgc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgc3Layout.setVerticalGroup(
            bgc3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgc5.setBackground(new java.awt.Color(0, 0, 0));

        subgc5.setBackground(new java.awt.Color(255, 255, 255));

        txtC5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtC5.setText("9");

        javax.swing.GroupLayout subgc5Layout = new javax.swing.GroupLayout(subgc5);
        subgc5.setLayout(subgc5Layout);
        subgc5Layout.setHorizontalGroup(
            subgc5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subgc5Layout.setVerticalGroup(
            subgc5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgc5Layout = new javax.swing.GroupLayout(bgc5);
        bgc5.setLayout(bgc5Layout);
        bgc5Layout.setHorizontalGroup(
            bgc5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgc5Layout.setVerticalGroup(
            bgc5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgc6.setBackground(new java.awt.Color(0, 0, 0));

        subgc6.setBackground(new java.awt.Color(255, 255, 255));

        txtC6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtC6.setText("9");

        javax.swing.GroupLayout subgc6Layout = new javax.swing.GroupLayout(subgc6);
        subgc6.setLayout(subgc6Layout);
        subgc6Layout.setHorizontalGroup(
            subgc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subgc6Layout.setVerticalGroup(
            subgc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgc6Layout = new javax.swing.GroupLayout(bgc6);
        bgc6.setLayout(bgc6Layout);
        bgc6Layout.setHorizontalGroup(
            bgc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgc6Layout.setVerticalGroup(
            bgc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgc8.setBackground(new java.awt.Color(0, 0, 0));

        subgc8.setBackground(new java.awt.Color(255, 255, 255));

        txtC8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtC8.setText("9");

        javax.swing.GroupLayout subgc8Layout = new javax.swing.GroupLayout(subgc8);
        subgc8.setLayout(subgc8Layout);
        subgc8Layout.setHorizontalGroup(
            subgc8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subgc8Layout.setVerticalGroup(
            subgc8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgc8Layout = new javax.swing.GroupLayout(bgc8);
        bgc8.setLayout(bgc8Layout);
        bgc8Layout.setHorizontalGroup(
            bgc8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgc8Layout.setVerticalGroup(
            bgc8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgc9.setBackground(new java.awt.Color(0, 0, 0));

        subgc9.setBackground(new java.awt.Color(255, 255, 255));

        txtC9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtC9.setText("9");
        txtC9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtC9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout subgc9Layout = new javax.swing.GroupLayout(subgc9);
        subgc9.setLayout(subgc9Layout);
        subgc9Layout.setHorizontalGroup(
            subgc9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subgc9Layout.setVerticalGroup(
            subgc9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgc9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtC9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgc9Layout = new javax.swing.GroupLayout(bgc9);
        bgc9.setLayout(bgc9Layout);
        bgc9Layout.setHorizontalGroup(
            bgc9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgc9Layout.setVerticalGroup(
            bgc9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgc9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgc9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgM.setBackground(new java.awt.Color(0, 0, 0));

        subgM.setBackground(new java.awt.Color(102, 102, 255));

        txtM.setFont(new java.awt.Font("Tahoma", 0, 150)); // NOI18N
        txtM.setForeground(new java.awt.Color(255, 255, 255));
        txtM.setText("9");

        javax.swing.GroupLayout subgMLayout = new javax.swing.GroupLayout(subgM);
        subgM.setLayout(subgMLayout);
        subgMLayout.setHorizontalGroup(
            subgMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subgMLayout.setVerticalGroup(
            subgMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgMLayout = new javax.swing.GroupLayout(bgM);
        bgM.setLayout(bgMLayout);
        bgMLayout.setHorizontalGroup(
            bgMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgMLayout.setVerticalGroup(
            bgMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subgM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bgc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bgc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bgc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bgc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bgc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bgc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bgc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 200, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bgCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bgM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bgCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciar)
                        .addComponent(btnAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bgc1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgc2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgc3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgc5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgc6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgc8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgc9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // Iniciar
        p.iniciar();
        llenarInterfaz();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Agregar jugadores
        //String player="";
        do{
            actual_player=javax.swing.JOptionPane.showInputDialog("Ingrese el nombre del jugador");
            if(actual_player.equals(""))
                javax.swing.JOptionPane.showMessageDialog(null,"Error, por favor ingrese un nombre para el jugador");
        }while(actual_player.equals(""));
        
        p.unirse(actual_player);
        
        //btnIniciar.setEnabled(p.getNoParticipantes()>1);
        btnIniciar.setEnabled(true);
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtC9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtC9MouseClicked
        // C9
        
        javax.swing.JOptionPane.showMessageDialog(null,"Usted selecciono la carta: "+txtC9.getText()+", "+bgc9.getBackground().toString());
    }//GEN-LAST:event_txtC9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }
    
    private void llenarInterfaz(){
        
        //Rellenar simbolos
        txtC1.setText(p.getJugador(actual_player).getMazo().get(0).getSimbolo());
        txtC2.setText(p.getJugador(actual_player).getMazo().get(1).getSimbolo());
        txtC3.setText(p.getJugador(actual_player).getMazo().get(2).getSimbolo());
        txtC5.setText(p.getJugador(actual_player).getMazo().get(3).getSimbolo());
        txtC6.setText(p.getJugador(actual_player).getMazo().get(4).getSimbolo());
        txtC8.setText(p.getJugador(actual_player).getMazo().get(5).getSimbolo());
        txtC9.setText(p.getJugador(actual_player).getMazo().get(6).getSimbolo());
        
        ArrayList<Carta> ma;
        
        ma=p.getJugador(actual_player).getMazo();
        
        //Carta 1
        switch (ma.get(0).getColor()) {
            case 1:
                bgc1.setBackground(Color.red);
                break;
            case 2:
                bgc1.setBackground(Color.green);
                break;
            case 3:
                bgc1.setBackground(Color.blue);
                break;
            case 4:
                bgc1.setBackground(Color.yellow);
                break;
            default:
                bgc1.setBackground(Color.black);
                break;
        }
        
        //Carta 2
        switch (ma.get(1).getColor()) {
            case 1:
                bgc2.setBackground(Color.red);
                break;
            case 2:
                bgc2.setBackground(Color.green);
                break;
            case 3:
                bgc2.setBackground(Color.blue);
                break;
            case 4:
                bgc2.setBackground(Color.yellow);
                break;
            default:
                bgc2.setBackground(Color.black);
                break;
        }
        
        //Carta 3
        switch (ma.get(2).getColor()) {
            case 1:
                bgc3.setBackground(Color.red);
                break;
            case 2:
                bgc3.setBackground(Color.green);
                break;
            case 3:
                bgc3.setBackground(Color.blue);
                break;
            case 4:
                bgc3.setBackground(Color.yellow);
                break;
            default:
                bgc3.setBackground(Color.black);
                break;
        }
        
        //Carta 4
        switch (ma.get(3).getColor()) {
            case 1:
                bgc5.setBackground(Color.red);
                break;
            case 2:
                bgc5.setBackground(Color.green);
                break;
            case 3:
                bgc5.setBackground(Color.blue);
                break;
            case 4:
                bgc5.setBackground(Color.yellow);
                break;
            default:
                bgc5.setBackground(Color.black);
                break;
        }
        
        //Carta 5
        switch (ma.get(4).getColor()) {
            case 1:
                bgc6.setBackground(Color.red);
                break;
            case 2:
                bgc6.setBackground(Color.green);
                break;
            case 3:
                bgc6.setBackground(Color.blue);
                break;
            case 4:
                bgc6.setBackground(Color.yellow);
                break;
            default:
                bgc6.setBackground(Color.black);
                break;
        }
        
        //Carta 6
        switch (ma.get(5).getColor()) {
            case 1:
                bgc8.setBackground(Color.red);
                break;
            case 2:
                bgc8.setBackground(Color.green);
                break;
            case 3:
                bgc8.setBackground(Color.blue);
                break;
            case 4:
                bgc8.setBackground(Color.yellow);
                break;
            default:
                bgc8.setBackground(Color.black);
                break;
        }
        
        //Carta 7
        switch (ma.get(6).getColor()) {
            case 1:
                bgc9.setBackground(Color.red);
                break;
            case 2:
                bgc9.setBackground(Color.green);
                break;
            case 3:
                bgc9.setBackground(Color.blue);
                break;
            case 4:
                bgc9.setBackground(Color.yellow);
                break;
            default:
                bgc9.setBackground(Color.black);
                break;
        }
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgCA;
    private javax.swing.JPanel bgM;
    private javax.swing.JPanel bgc1;
    private javax.swing.JPanel bgc2;
    private javax.swing.JPanel bgc3;
    private javax.swing.JPanel bgc5;
    private javax.swing.JPanel bgc6;
    private javax.swing.JPanel bgc8;
    private javax.swing.JPanel bgc9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel subgCA;
    private javax.swing.JPanel subgM;
    private javax.swing.JPanel subgc1;
    private javax.swing.JPanel subgc2;
    private javax.swing.JPanel subgc3;
    private javax.swing.JPanel subgc5;
    private javax.swing.JPanel subgc6;
    private javax.swing.JPanel subgc8;
    private javax.swing.JPanel subgc9;
    private javax.swing.JLabel txtC1;
    private javax.swing.JLabel txtC2;
    private javax.swing.JLabel txtC3;
    private javax.swing.JLabel txtC5;
    private javax.swing.JLabel txtC6;
    private javax.swing.JLabel txtC8;
    private javax.swing.JLabel txtC9;
    private javax.swing.JLabel txtCA;
    private javax.swing.JLabel txtM;
    // End of variables declaration//GEN-END:variables
}
